FROM ghcr.io/runatlantis/atlantis:{latest version}

LABEL org.opencontainers.image.source=https://github.com/carendell-atscale/atlantis-fullbuild/
LABEL org.opencontainers.image.description="A customized clone of Atlantis to add multiple libraries and configuration"
LABEL org.opencontainers.image.licenses=MIT