name: 'Workflow :: PR'


on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  packages: write


jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          dockerfile: ./docker/deploy/Dockerfile
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref }}
            ghcr.io/${{ github.repository }}:latest

      